org:
  quartz:
    scheduler:
      instanceName: spring-boot-quartz-demo
      instanceId: AUTO
    threadPool:
      threadCount: 5

job:
  startDelay: 0
  repeatInterval: 60000
  description: Hello Job
  key: HelloJob

jsondoc:
  version: 1.0
  basePath: http://localhost:8080
  packages: ['hello']
